version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
  php:
    image: php:8.2-fpm
    volumes:
      - ./:/var/www